# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c019915e5cdf72d6a20410a4d64d28dcc7f1e630dcf91830e84ebe4cf56573b294e46e163679316daf174c7f78d414b0b89ba2e7d91ac578a19993b392e221a5

test:
  secret_key_base: 07ff631379488cb90bd723a46d86ca753053b7dc02067181f53cd3859aac9af9d431820eda343d623e80e4685a7990fe7adcccfd8549bfcbe2e8375a16139186

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
