# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a7a973a64e730f5093abb38522f6b7b13c0e291bef1a0b7fa427091e9f02b415fe277ab2d7c45d86673a1d61bfe9104ff4fb87c278bc594e880abab2273afc10

test:
  secret_key_base: b229233c6fd411c3c5c09d9e0152c2a19226ca5153c8ffccdc76fe9b89d0d1a9893520f9b21994e6fe08eb53da4e4fa55da5b4d67a59cec1eedaf39c2a4b4e09

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
